### ISSUE TITLE
`version` must be set before `data` in the modulemd when dependencies are specified

### ISSUE THREAD

**Issue by mprahl** [fedora-modularity/libmodulemd#14]
When loading a modulemd from a file, the following fails with "Invalid document [Unknown modulemd version]. Skipping it":
```yaml
document: modulemd
data:
    dependencies:
        buildrequires:
            platform: f28
        requires:
            platform: f28
version: 1
```

When specifying the version before `dependencies` is processed, it works as expected.
```yaml
document: modulemd
version: 1
data:
    dependencies:
        buildrequires:
            platform: f28
        requires:
            platform: f28
```

I'm not sure how to workaround this in MBS as both should be valid modulemds, or at least they were in the Python implementation of modulemd.
