### ISSUE TITLE
Strange unicode behaviour with `dumps`

### ISSUE THREAD

**Issue by hanzz** [fedora-modularity/libmodulemd#183]
Execute http://jkaluza.fedorapeople.org/mmd.py. The resulting yaml escapes emoticon, but keeps the second character as it is.

**Comment by ignatenkobrain** [comment]
```
^[[A⏎                                                                                                                                       ⋊> ~ python2 f.py                                                                                                                   12:50:03
('Modulemd.get_version() ==', '2.1.0')
Traceback (most recent call last):
  File "f.py", line 37, in <module>
    mmd = Modulemd.Module.new_from_string(data)
AttributeError: type object 'Module' has no attribute 'new_from_string'
```

**Comment by hanzz** [comment]
You have too new libmodulemd :).

**Comment by hanzz** [comment]
latest available for me is libmodulemd-1.7.0-1.fc28.x86_64. I can try with 2.x.y too.

**Comment by sgallagher** [comment]
The submitted script does not specify the API version to use, so if you have 2.0 available, it tries to use that and fails. Replace the top few lines with
```
import gi
gi.require_version('Modulemd', '1.0')
from gi.repository import Modulemd
```
To force it to use the 1.0 API (assuming you have the python-libmodulemd1 package installed)

I can reproduce the issue on 1.8.2. I need to keep digging to figure out why this is happening.

**Comment by sgallagher** [comment]
For the record:

```
# -*- coding: utf-8 -*-
import gi
gi.require_version('Modulemd', '2.0')
from gi.repository import Modulemd
print("Modulemd.get_version() ==", Modulemd.get_version())
data = """
document: modulemd
version: 2
data:
  name: testmodule
  stream: private-mprahl-rhel-8.0.0
  version: 820181212163733
  context: 9edba152
  arch: x86_64
  summary: A test module in all its beautiful beauty.
  description: >-
    Two unicode chars: 😄 ’
  license:
    module:
    - MIT
    content:
    - GPLv2+
    - GPLv3+
    - LGPLv2+
  dependencies:
  - buildrequires:
      platform: [el8]
    requires:
      platform: [el8]
  references:
    community: https://fedoraproject.org/wiki/Modularity
    documentation: https://fedoraproject.org/wiki/Fedora_Packaging_Guidelines_for_Modules
    tracker: https://taiga.fedorainfracloud.org/project/modularity
"""

index = Modulemd.ModuleIndex.new()
index.update_from_string(data, True)
data = index.dump_to_string()

print(type(data))
print(data)
```

This is a 2.0 API version that also has the same problem. I'm looking into whether the issue is with libmodulemd, libyaml or GObject Introspection.
