### ISSUE TITLE
RFE: add flags to include packages in (srpm-)buildroot

### ISSUE THREAD

**Issue by ignatenkobrain** [fedora-modularity/libmodulemd#288]
Imagine that I have 2 components, `rust-srpm-macros` which defines `%{rust_arches}` and `rust` which is using it in `ExclusiveArch`. The former one has to be in srpm-buildroot in order for latter to build. That means, at this point I have only option to use 2 module (rust and rust-bootstrap).. But rust needs its own bootstrapping, so I would need to have 3 modules.

Having something like:

```yaml
rpms:
  rust-srpm-macros:
    rationale: Main component.
    srpm-buildroot: true
  rust:
    rationale: Main component.
    buildafter: [rust-srpm-macros]
```

Would be good. Also for completeness, adding `buildroot` flag.

**Comment by ignatenkobrain** [comment]
As discussed with @contyk in a pub :)

**Comment by ignatenkobrain** [comment]
@mprahl @jkaluza how hard would this be to implement in MBS?

**Comment by mprahl** [comment]
@ignatenkobrain this shouldn't be too hard in MBS. If this becomes part of the libmodulemd spec, we can support it in MBS.

Adding @lcarva for visibility.

**Comment by mprahl** [comment]
@ignatenkobrain I noticed that in your example that you use `buildafter`. Would this feature still be useful to you even without `buildafter`? I ask because supporting `buildafter` is a lot more work, and the earliest we'll be able to work on that is in June (likely later).

**Comment by sgallagher** [comment]
@ignatenkobrain @mprahl This slipped off my radar. Is this still something that is desired? I can get it into 2.7.0 if so.

**Comment by ignatenkobrain** [comment]
Yes, please.

**Comment by sgallagher** [comment]
@mmathesius Would you please add a new boolean attribute to `ModulemdComponentRpm`, along with the appropriate getter, setter and tests?

**Comment by mmathesius** [comment]
Just to make sure I've got the semantics right, is https://github.com/mmathesius/libmodulemd/commit/f035b2754e4abdab502ac0e46f0c2aeb3b7a98a4 an accurate representation of the spec change corresponding to this RFE?

**Comment by sgallagher** [comment]
Hmm, I'm not sure exactly what the point of the `buildroot` argument would be here. The `srpm-buildroot` makes sense, but `buildroot` should just be handled by the `buildorder/buildafter` functionality, I think.

@ignatenkobrain Can you explain why you think `buildroot` is useful?

**Comment by ignatenkobrain** [comment]
`buildorder/buildafter` does not control default set of packages in the buildroot. Yes, packages can BuildRequires those... But I wanted it for completness. Like if you can specify it in profile and it is inherited by MBS, why do one part and not another?

https://github.com/fedora-modularity/libmodulemd/blob/master/spec.v2.yaml#L177-L190

**Comment by sgallagher** [comment]
Okay, I guess it’s fine to include it and rarely use it.

@mmathesius please update the spec to explain that the purpose is to force it into the buildroot even if not explicitly in BuildRequires. That should obviously imply defaulting to False as well.

**Comment by ignatenkobrain** [comment]
Probably include reference to `srpm-buildroot` and `buildroot` profiles’ description…

**Comment by sgallagher** [comment]
@ignatenkobrain More information, please? Are there some special-cases profiles we need to document?

**Comment by ignatenkobrain** [comment]
@sgallagher sorry for not being very clear. In the spec.v2.yaml we have some documentation what purpose `srpm-buildroot` and `buildroot` are serving. This is essentially same, but within a module.

**Comment by sgallagher** [comment]
@ignatenkobrain Thanks.

@mmathesius So I think the spec here should be:

```yaml
# If buildroot is set to True, the packages listed in this module's buildroot profile will be installed into
# the buildroot of any component built after this one, even if that module does not explicitly include
# these packages in its BuildRequires.
# Defaults to "false" if not specified.
buildroot: false
# If buildroot is set to True, the packages listed in this module's srpm-buildroot profile will be installed
# into the buildroot when performing the buildSRPMfromSCM step.
# Defaults to "false" if not specified.
srpm-buildroot: false
```
