### ISSUE TITLE
Emitted yaml for an empty ModuleDependencies

### ISSUE THREAD

**Issue by owtaylor** [fedora-modularity/libmodulemd#340]
``` python
gi.require_version('Modulemd', '2.0')
from gi.repository import Modulemd
st = Modulemd.ModuleStreamV2(stream_name='master', module_name='eog')
st.set_summary('Foo')
st.set_description('Bar')
st.add_module_license('MIT')
st.add_dependencies(Modulemd.Dependencies())
st.validate()
True
index = Modulemd.ModuleIndex()
index.add_module_stream(st)
print(index.dump_to_string())
```
``` yaml
---
document: modulemd
version: 2
data:
  name: eog
  stream: master
  summary: Foo
  description: >-
    Bar
  license:
    module:
    - MIT
  dependencies: []
...
```

Where I would expect `dependencies: [{}]`

 * it seems logically consistent to me - things in the dependency lists are different options for the dependencies of the modules - and one valid option for dependencies is "no dependencies"
 * libmodulemd otherwise considers empty dependency objects valid 
 * libomodulemd will read `dependencies: [{}]` and create the expected structures - they just disappear when writing back out.
 * libmodulemd v1 behaved this way

The way this particularly broke me with the v2 API transition, was that I had some code that did "look for X in the dependencies of a built module" - and since a built module has only one option for the dependencies - it expected that it could just do get_dependencies()[0] - then I had test code that removed X from the dependencies of the module to test the failure path, and since that left things empty, get_dependencies()[0] no longer worked.

I think MBS now requires buildrequires: platform in all cases, so "built module with empty dependencies" is artificial.
