### ISSUE TITLE
Do not warn about missing stream from profile defaults.

### ISSUE THREAD

**Issue by dmach** [fedora-modularity/libmodulemd#43]
Example data:
```
document: modulemd-defaults
version: 1
data:
  module: testmodule
  stream: 2.0
  profiles:
    master: [default]
```

This triggers following output:
```
** Message: 09:15:48.608: Default stream missing from profile defaults
** Message: 09:15:48.608: Invalid [ModulemdDefaults] document [Default stream missing from profile defaults].
** Message: 09:15:48.608: Invalid document [Default stream missing from profile defaults]. Skipping it.
```
I think this behavior is incorrect. Consider following use cases:

1. specify default stream only; use the 'default' profile in modulemd or the empty 'default' fallback
2. override installation profiles without touching the default stream (or eventually don't have a default at all)
