### ISSUE TITLE
Defining one default profile for all streams

### ISSUE THREAD

**Issue by LorbusChris** [fedora-modularity/libmodulemd#580]
For modules that release new streams frequently, it would be useful to allow for one default profile for all streams, so the new streams wouldn't have to be added to the defaults file each time.

Example:
```
document: modulemd-defaults
version: 1
data:
    module: cri-o
    profiles:
        '*': [default]
```
