### ISSUE TITLE
buildorder: -1 is broken

### ISSUE THREAD

**Issue by hanzz** [fedora-modularity/libmodulemd#77]
```
from gi import Repository
r = Repository.get_default() # noqa
r.require('Modulemd') # noqa
from gi.repository import Modulemd

data = """
document: modulemd
version: 1
data:
    summary: A test module in all its beautiful beauty.
    description: This module demonstrates how to write simple modulemd files And can be used for testing the build and release pipeline.
    license:
        module: [ MIT ]
    dependencies:
        buildrequires:
            platform: el8
        requires:
            platform: el8
    references:
        community: https://fedoraproject.org/wiki/Modularity
        documentation: https://fedoraproject.org/wiki/Fedora_Packaging_Guidelines_for_Modules
        tracker: https://taiga.fedorainfracloud.org/project/modularity
    profiles:
        default:
            rpms:
                - tangerine
    api:
        rpms:
            - perl-Tangerine
            - tangerine
    components:
        rpms:
            attr:
                rationale: A build dependency of acl
                ref: rhel-8.0
                buildorder: -1
"""

mmd = Modulemd.Module.new_from_string(data)
mmd.upgrade()
print mmd.get_rpm_components().values()[0].get_buildorder()

```

```
$ python mmd.py 
18446744073709551615
```
